version: '3'
services:

#  iot:
#    container_name: fox-iot
#    build:
#      context: iot
#      dockerfile: ../docker/Dockerfile-iot-go
#    ports:
#      - '2006:2006'
#    volumes:
#      - '.:/go/src/app/dawMp'
#    env_file:
#      - .env
#    networks:
#      - foxtrot-api-lan
#      - foxtrot-bridge

  php8:
    container_name: fox-php8
    hostname: php8.fox
    build:
      context: back-php/
      dockerfile: ../docker/Dockerfile-php
    volumes:
      - './back-php/api/:/var/www/html/api'
      - './.env:/var/www/html/api/.env'
    ports:
      - '2003:80'
    env_file:
      - .env
    environment:
      LEAF_DEV_TOOLS: 'true'
      TZ: Europe/Madrid
    networks:
      - foxtrot-bridge
      - foxtrot-api-lan
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    working_dir: /var/www/html/api
    command: [
      'bash',
      '-c',
      'composer update && apache2-foreground'
    ]


  phpdoc:
    container_name: fox-phpdoc
    image: phpdoc/phpdoc
    environment:
      TZ: Europe/Madrid
    volumes:
      - './back/api/app:/data'
      - './docs/phpdoc:/output'
    networks:
      - foxtrot-bridge
      - foxtrot-api-lan
    command: [ "-d", "/data", "-t", "/output", "-s", "template.color=deep-purple" ]

  mysql:
    container_name: fox-mysql
    hostname: mysql.fox
    image: mysql:latest
    volumes:
      - fox-eagle-db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '2005:3306'
    environment:
      TZ: Europe/Madrid
    env_file:
      - .env
    networks:
      - foxtrot-bridge
      - foxtrot-api-lan

networks:
  foxtrot-api-lan:
    internal: true
  foxtrot-bridge:
    driver: bridge
volumes:
  fox-eagle-db:
  fox-bun:
  fox-php: