version: '3'
services:
  php8:
    container_name: fox-php8
    hostname: php8.docker
    build:
      context: docker
      dockerfile: Dockerfile-php
    volumes:
      - './www/:/var/www/html/'
    ports:
      - "8080:80"
    tty: true
    working_dir: /var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
    networks:
      - dwcs
    extra_hosts:
      - "host.docker.internal:host-gateway"


  mysql:
    container_name: dwcs-mysql
    hostname: mysql.docker
    image: mysql:latest
    volumes:
      - dwcs-db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: dwcs
    networks:
      - dwcsLan
      - dwcs

  phpmyadmin:
    container_name: dwcs-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    hostname: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dwcs

    networks:
      - dwcsLan
      - dwcs

networks:
  dwcsLan:
    internal: true
  dwcs:
    driver: bridge
volumes:
  dwcs-db: