version: '3'
services:
  webhook:
    container_name: fox-webhook
    build:
      context: webhook
      dockerfile: ../docker/Dockerfile-webhook-go
    ports:
      - '2002:2002'
    volumes:
      - '.:/go/src/app/dawMp'
    env_file:
      - .env
    networks:
      - foxtrot-bridge

  iot:
    container_name: fox-iot
    build:
      context: iot
      dockerfile: ../docker/Dockerfile-iot-go
    ports:
      - '2006:2006'
    volumes:
      - '.:/go/src/app/dawMp'
    env_file:
      - .env
    networks:
      - foxtrot-bridge

  php8:
    container_name: fox-php8
    hostname: php8.fox
    build:
      context: back/
      dockerfile: ../docker/Dockerfile-php
    volumes:
      - './back/api/:/var/www/html/api'
      - './.env:/var/www/html/api/.env'
    ports:
      - '2003:80'
    env_file:
      - .env
    environment:
      LEAF_DEV_TOOLS: 'true'
    networks:
      - foxtrot-bridge
      - foxtrot-api-lan
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    working_dir: /var/www/html/api
    command: [
      'bash',
      '-c',
      'composer update && apache2-foreground'
    ]

  bun:
    container_name: fox-bun
    hostname: bun.fox
    build:
      context: front/
      dockerfile: ../docker/Dockerfile-bunjs
    working_dir: /app
    volumes:
      - fox-bun:/app/
    environment:
      - REACT_APP_PHP_SERVER = "https://api.foxtrot.pedroseoaneprado.es"
    ports:
      - '2004:2024'
    networks:
      - foxtrot-bridge
    command: [ 'sh', '-c', 'bun run dev' ]

  mysql:
    container_name: fox-mysql
    hostname: mysql.fox
    image: mysql:latest
    volumes:
      - fox-eagle-db:/var/lib/mysql
    ports:
      - '2005:3306'
    env_file:
      - .env
    networks:
      - foxtrot-api-lan

networks:
  foxtrot-api-lan:
    internal: true
  foxtrot-bridge:
    driver: bridge
volumes:
  fox-eagle-db:
  fox-bun:
  fox-php: