version: '3'
services:
  php8:
    container_name: fox-php8
    hostname: php8.fox
    build:
      context: back/
      dockerfile: ../docker/Dockerfile-php
    volumes:
      - './back/www/:/var/www/html/'
    ports:
      - "2003:80"
    tty: true
    working_dir: /var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
    networks:
      - foxtrot-bridge
      - foxtrot-api-lan
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nodejs:
    container_name: fox-nodejs
    hostname: nodejs.fox
    build:
      context: front/
      dockerfile: ../docker/Dockerfile-bunjs
    volumes:
      - './front/:/app/'
    ports:
      - "2004:2004"
    networks:
      - foxtrot-bridge
      - foxtrot-api-lan

  mariadb:
    container_name: fox-mariadb
    hostname: mariadb.fox
    image: mariadb:latest
    volumes:
      - foxtrot-db:/var/lib/mysql
    ports:
      - "2005:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: dwcs
    networks:
      - foxtrot-bridge
      - foxtrot-api-lan

networks:
  foxtrot-api-lan:
    internal: true
  foxtrot-bridge:
    driver: bridge
volumes:
  foxtrot-db: