FROM golang:latest AS golang-builder

RUN --mount=type=cache,target=/var/cache/apt apt update  && apt install -qy git
WORKDIR /go/src/app
RUN git config --global --add safe.directory /go/src/app/dawMp
COPY . .
RUN go build -o go-webhook .
CMD ["./go-webhook"]