FROM golang:latest AS golang-builder

RUN curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

RUN apt update && apt install -qy git

WORKDIR /go/src/app
COPY . .
RUN go build -o go-webhook .
CMD ["./go-webhook"]
