# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun
WORKDIR /app
COPY ./package.json ./
COPY ./bun.lockb ./
COPY vite.config.js ./
RUN bun install --save-dev

USER bun

CMD [ "bun","run","dev"]