# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun
WORKDIR /app
COPY package.json /app
RUN bun i @rollup/rollup-linux-x64-gnu
RUN bun i --save-dev
COPY . /app