name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and run Doxygen container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/back-php/api:/data \
            -v ${{ github.workspace }}/docs/doxygen:/output \
            -w /data \
            -e TZ=Europe/Madrid \
            greenbone/doxygen \
            sh -c "doxygen Doxyfile"

      - name: Upload Doxygen documentation
        uses: actions/upload-artifact@v2
        with:
          name: doxygen-docs
          path: docs/doxygen
